syntax on

" Vim Plug
call plug#begin()


call plug#end()

filetype plugin on

set noerrorbells
set tabstop=4 softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nu
set relativenumber
set nowrap
set smartcase
set noswapfile
set nobackup
set undodir=~/.vim/undodir
set undofile
set incsearch
set hidden
set scrolloff=8

set signcolumn=yes
set colorcolumn=80

set updatetime=50

set cmdheight=2

"ColorColumn ctermbg=0 guibg=lightgrey
