return {
	"nvim-treesitter/nvim-treesitter",
	branch = "master",
	lazy = false,
	build = ":TSUpdate",
	main = "nvim-treesitter.configs",
	opts = {
		ensure_installed = {
			"bash",
			"bicep",
			"dockerfile",
			"git_config",
			"javascript",
			"json",
			"lua",
			"markdown",
			"markdown_inline",
			"nginx",
			"python",
			"ssh_config",
			"tmux",
			"toml",
			"typescript",
			"vimdoc",
			"yaml",
		},
		auto_install = true,
		highlight = { enable = true },
		indent = { enable = true },
		additional_vim_regex_highlighting = false,
	},
}
